---
- hosts: Dev[0]
  become: true
  tasks:
    - name: direcotry
      file:
        path: /tmp/class
        state: directory
        mode: '0755'

    - name: upgrade all packages
      yum:
         name: '*'
         state: latest
    - name: httpd sevice
      yum:
        name: httpd
        state: latest
