---
# tasks file for tomcat

# tasks file for tomcat9


- name: install the latest version of java
  yum:
    name: java-11-openjdk
    state: latest

- name: Create tomcat group
  group:
    name: tomcat
    state: present


- name: create a tomcat user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat


- name: Create a tomcat directory and Grant permission
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'
    owner: tomcat
    group: tomcat
    recurse: yes



- name: Download tomcat
  get_url:
    url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz   
    dest: /opt/tomcat


- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "/opt/tomcat/apache-tomcat-9.0.78.tar.gz"
    dest: /opt/tomcat/
    remote_src: yes
    mode: 0755
    owner: tomcat
    group: tomcat



- name: copy tomcat-users.xml to tomcat_home/conf
  copy:
    src: /home/ansib/ansible-playrole.yml/tomcat/files/tomcat-users.xml
    dest: /opt/tomcat/apache-tomcat-9.0.78/conf
    remote_src: no
    owner: tomcat
    group: tomcat
    mode: 0755


- name: copy context.xml to tomcat_home/meta-inf
  copy:
    src: /home/ansib/ansible-playrole.yml/tomcat/files/context.xml
    dest: /opt/tomcat/apache-tomcat-9.0.78/webapps/manager/META-INF/context.xml
    remote_src: no
    owner: tomcat
    group: tomcat
    mode: 0755



- name: copy tomcat service to systemd
  copy:
    src:  /home/ansib/ansible-playrole.yml/tomcat/files/tomcat.service
    dest: /etc/systemd/system/
    remote_src: no
    owner: root
    group: root
    mode: 0755

- name: reload tomcat service
  systemd:
    daemon_reload: yes

- name: Start tomcat service
  service:
    name: tomcat.service
    state: started

- name: Enable tomcat service
  service:
    name: tomcat.service
    enabled: yes
  notify:
    - Restart tomcat service
